# Generated by Django 5.2.8 on 2025-11-21 08:13

import django.core.validators
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, help_text='Uploaded file (max 5MB)', max_length=500, null=True, upload_to=notifications.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'zip', 'jpg', 'jpeg', 'png'])], verbose_name='Attachment File'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.CharField(blank=True, max_length=150, verbose_name='Company/Organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='service',
            field=models.CharField(blank=True, choices=[('AI Services', 'AI Services'), ('Website Development', 'Website Development'), ('Mobile App Development', 'Mobile App Development'), ('Branding & Design', 'Branding & Design'), ('Bulk SMS Integration', 'Bulk SMS Integration'), ('IT Consulting', 'IT Consulting'), ('Other', 'Other')], max_length=50, verbose_name='Service Interested In'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Business Email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
